const countryCodeList = [{
    "name": "Angola",
    "code": "+244"
}, {
    "name": "Afghanistan",
    "code": "+93"
}, {
    "name": "Albania",
    "code": "+355"
}, {
    "name": "Algeria",
    "code": "+2"
}, {
    "name": "Andorra",
    "code": "+376"
}, {
    "name": "Anguilla",
    "code": "+1264"
}, {
    "name": "Antigua and Barbuda",
    "code": "+1268"
}, {
    "name": "Argentina",
    "code": "+54"
}, {
    "name": "Armenia",
    "code": "+374"
}, {
    "name": "Ascension",
    "code": "+247"
}, {
    "name": "Australia",
    "code": "+61"
}, {
    "name": "Austria",
    "code": "+43"
}, {
    "name": "Azerbaijan",
    "code": "+994"
}, {
    "name": "Bahamas",
    "code": "+1242"
}, {
    "name": "Bahrain",
    "code": "+973"
}, {
    "name": "Bangladesh",
    "code": "+880"
}, {
    "name": "Barbados",
    "code": "+1246"
}, {
    "name": "Belarus",
    "code": "+375"
}, {
    "name": "Belgium",
    "code": "+32"
}, {
    "name": "Belize",
    "code": "+501"
}, {
    "name": "Benin",
    "code": "+229"
}, {
    "name": "BermudaIs",
    "code": "+1441"
}, {
    "name": "Bolivia",
    "code": "+267"
}, {
    "name": "Botswana",
    "code": "+994"
}, {
    "name": "Brunei",
    "code": "+673"
}, {
    "name": "Bulgaria",
    "code": "+359"
}, {
    "name": "Burkinafaso",
    "code": "+226"
}, {
    "name": "Burma",
    "code": "+95"
}, {
    "name": "Burundi",
    "code": "+257"
}, {
    "name": "Cameroon",
    "code": "+237"
}, {
    "name": "Canada",
    "code": "+1"
}, {
    "name": "Cayman Is",
    "code": "+1345"
}, {
    "name": "Central African Republic",
    "code": "+236"
}, {
    "name": "Chad",
    "code": "+235"
}, {
    "name": "Chile",
    "code": "+56"
}, {
    "name": "China",
    "code": "+86"
}, {
    "name": "Colombia",
    "code": "+57"
}, {
    "name": "Congo",
    "code": "+242"
}, {
    "name": "Cook Is",
    "code": "+682"
}, {
    "name": "Costa Rica",
    "code": "+506"
}, {
    "name": "Cuba",
    "code": "+53"
}, {
    "name": "Cyprus",
    "code": "+357"
}, {
    "name": "Czech Republic",
    "code": "+420"
}, {
    "name": "Denmark",
    "code": "+45"
}, {
    "name": "Ecuador",
    "code": "+593"
}, {
    "name": "Egypt",
    "code": "+20"
}, {
    "name": "EISalvador",
    "code": "+503"
}, {
    "name": "Estonia",
    "code": "+372"
}, {
    "name": "Ethiopia",
    "code": "+251"
}, {
    "name": "Fiji",
    "code": "+679"
}, {
    "name": "Finland",
    "code": "+358"
}, {
    "name": "France",
    "code": "+33"
}, {
    "name": "French Guiana",
    "code": "+594"
}, {
    "name": "Gabon",
    "code": "+241"
}, {
    "name": "Gambia",
    "code": "+220"
}, {
    "name": "Germany",
    "code": "+49"
}, {
    "name": "Georgia",
    "code": "+995"
}, {
    "name": "Ghana",
    "code": "+233"
}, {
    "name": "Gibraltar",
    "code": "+350"
}, {
    "name": "Greece",
    "code": "+30"
}, {
    "name": "Grenada",
    "code": "+1809"
}, {
    "name": "Guam",
    "code": "+1671"
}, {
    "name": "Haiti",
    "code": "+509"
}, {
    "name": "Honduras",
    "code": "+504"
}, {
    "name": "Hongkong",
    "code": "+852"
}, {
    "name": "Hungary",
    "code": "+36"
}, {
    "name": "Gibraltar",
    "code": "+350"
}, {
    "name": "Iceland",
    "code": "+354"
}, {
    "name": "India",
    "code": "+91"
}, {
    "name": "Indonesia",
    "code": "+62"
}, {
    "name": "Iran",
    "code": "+98"
}, {
    "name": "Iraq",
    "code": "+964"
}, {
    "name": "Ireland",
    "code": "+353"
}, {
    "name": "Israel",
    "code": "+972"
}, {
    "name": "Italy",
    "code": "+39"
}, {
    "name": "IvoryCoast",
    "code": "+225"
}, {
    "name": "Jamaica",
    "code": "+1876"
}, {
    "name": "Japan",
    "code": "+81"
}, {
    "name": "Jordan",
    "code": "+962"
}, {
    "name": "Kampuchea",
    "code": "+855"
}, {
    "name": "Kazakstan",
    "code": "+327"
}, {
    "name": "Kenya",
    "code": "+254"
}, {
    "name": "Korea",
    "code": "+82"
}, {
    "name": "Kuwait",
    "code": "+965"
}, {
    "name": "Kyrgyzstan",
    "code": "+331"
}, {
    "name": "Laos",
    "code": "+856"
}, {
    "name": "Latvia",
    "code": "+371"
}, {
    "name": "Lebanon",
    "code": "+961"
}, {
    "name": "Lesotho",
    "code": "+266"
}, {
    "name": "Liberia",
    "code": "+231"
}, {
    "name": "Libya",
    "code": "+218"
}, {
    "name": "Liechtenstein",
    "code": "+423"
}, {
    "name": "Lithuania",
    "code": "+370"
}, {
    "name": "Luxembourg",
    "code": "+352"
}, {
    "name": "Macao",
    "code": "+853"
}, {
    "name": "Madagascar",
    "code": "+261"
}, {
    "name": "Malawi",
    "code": "+265"
}, {
    "name": "Malaysia",
    "code": "+60"
}, {
    "name": "Maldives",
    "code": "+960"
}, {
    "name": "Mali",
    "code": "+223"
}, {
    "name": "Malta",
    "code": "+356"
}, {
    "name": "Mariana Is",
    "code": "+1670"
}, {
    "name": "Martinique",
    "code": "+596"
}, {
    "name": "Mauritius",
    "code": "+230"
}, {
    "name": "Mexico",
    "code": "+52"
}, {
    "name": "Moldova",
    "code": "+373"
}, {
    "name": "Monaco",
    "code": "+377"
}, {
    "name": "Mongolia",
    "code": "+976"
}, {
    "name": "Montserrat Is",
    "code": "+1664"
}, {
    "name": "Morocco",
    "code": "+212"
}, {
    "name": "Mozambique",
    "code": "+258"
}, {
    "name": "Namibia",
    "code": "+264"
}, {
    "name": "Nauru",
    "code": "+674"
}, {
    "name": "Nepal",
    "code": "+977"
}, {
    "name": "Netheriands Antilles",
    "code": "+599"
}, {
    "name": "Netherlands",
    "code": "+31"
}, {
    "name": "NewZealand",
    "code": "+64"
}, {
    "name": "Nicaragua",
    "code": "+505"
}, {
    "name": "Niger",
    "code": "+227"
}, {
    "name": "Nigeria",
    "code": "+234"
}, {
    "name": "North Korea",
    "code": "+850"
}, {
    "name": "Norway",
    "code": "+47"
}, {
    "name": "Oman",
    "code": "+968"
}, {
    "name": "Pakistan",
    "code": "+92"
}, {
    "name": "Panama",
    "code": "+507"
}, {
    "name": "Papua New Cuinea",
    "code": "+675"
}, {
    "name": "Paraguay",
    "code": "+595"
}, {
    "name": "Peru",
    "code": "+51"
}, {
    "name": "Philippines",
    "code": "+63"
}, {
    "name": "Poland",
    "code": "+48"
}, {
    "name": "French Polynesia",
    "code": "+689"
}, {
    "name": "Portugal",
    "code": "+351"
}, {
    "name": "PuertoRico",
    "code": "+1787"
}, {
    "name": "Qatar",
    "code": "+974"
}, {
    "name": "Reunion",
    "code": "+262"
}, {
    "name": "Romania",
    "code": "+40"
}, {
    "name": "Russia",
    "code": "+7"
}, {
    "name": "Saint Lueia",
    "code": "+1758"
}, {
    "name": "Saint Vincent",
    "code": "+1784"
}, {
    "name": "Samoa Eastern",
    "code": "+684"
}, {
    "name": "Samoa Western",
    "code": "+685"
}, {
    "name": "San Marino",
    "code": "+378"
}, {
    "name": "Sao Tome and Principe",
    "code": "+239"
}, {
    "name": "Saudi Arabia",
    "code": "+966"
}, {
    "name": "Senegal",
    "code": "+221"
}, {
    "name": "Seychelles",
    "code": "+248"
}, {
    "name": "Sierra Leone",
    "code": "+232"
}, {
    "name": "Singapore",
    "code": "+65"
}, {
    "name": "Slovakia",
    "code": "+421"
}, {
    "name": "Slovenia",
    "code": "+386"
}, {
    "name": "Solomon Is",
    "code": "+677"
}, {
    "name": "Somali",
    "code": "+252"
}, {
    "name": "South Africa",
    "code": "+27"
}, {
    "name": "Spain",
    "code": "+34"
}, {
    "name": "Sri Lanka",
    "code": "+94"
}, {
    "name": "St.Lucia",
    "code": "+1758"
}, {
    "name": "St.Vincent",
    "code": "+1784"
}, {
    "name": "Sudan",
    "code": "+249"
}, {
    "name": "Suriname",
    "code": "+597"
}, {
    "name": "Swaziland",
    "code": "+268"
}, {
    "name": "Sweden",
    "code": "+46"
}, {
    "name": "Switzerland",
    "code": "+41"
}, {
    "name": "Syria",
    "code": "+963"
}, {
    "name": "Taiwan",
    "code": "+886"
}, {
    "name": "Tajikstan",
    "code": "+992"
}, {
    "name": "Tanzania",
    "code": "+255"
}, {
    "name": "Thailand",
    "code": "+66"
}, {
    "name": "Togo",
    "code": "+228"
}, {
    "name": "Tonga",
    "code": "+676"
}, {
    "name": "Trinidad and Tobago",
    "code": "+1809"
}, {
    "name": "Tunisia",
    "code": "+216"
}, {
    "name": "Turkey",
    "code": "+90"
}, {
    "name": "Turkmenistan",
    "code": "+993"
}, {
    "name": "Uganda",
    "code": "+256"
}, {
    "name": "Ukraine",
    "code": "+380"
}, {
    "name": "United Arab Emirates",
    "code": "+971"
}, {
    "name": "United Kiongdom",
    "code": "+44"
}, {
    "name": "United States of America",
    "code": "+1"
}, {
    "name": "Uruguay",
    "code": "+598"
}, {
    "name": "Uzbekistan",
    "code": "+233"
}, {
    "name": "Venezuela",
    "code": "+58"
}, {
    "name": "Vietnam",
    "code": "+84"
}, {
    "name": "Yemen",
    "code": "+967"
}, {
    "name": "Yugoslavia",
    "code": "+381"
}, {
    "name": "Zimbabwe",
    "code": "+263"
}, {
    "name": "Zaire",
    "code": "+243"
}, {
    "name": "Zambia",
    "code": "+260"
}];

module.exports = countryCodeList